Анастасия Плавина

## Тема: Системы линейных уравнений. Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1 \\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3 \\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

(из 3 строки отнимаем первую, из 2 строки отнимаем удвоенную первую строку)


Система имеет бесконечное число решений:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
x_{3}=-\frac{4-3x_{4}}{2}.
\end{cases}$

$\begin{cases}
x_{1}+6.5x_{4}-(-2 + 1.5x_{4})-2x_{4}=0, \\
x_{2} = 6.5x_{4}, \\
x_{3}=-2 + 1.5x_{4} .
\end{cases}$

$\begin{cases}
x_{1}= -3x_{4}-2, \\
x_{2} = 6.5x_{4}, \\
x_{3}=-2 + 1.5x_{4} .
\end{cases}$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Решение

а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$

Вычтем удвоеную третью строку из второй:

$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
0 & -7 & -1 \\
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$

Вычтем утроенную третью строку из первой:

$\begin{pmatrix}
\left.\begin{matrix}
0 & -4 & 4 \\ 
0 & -7 & -1 \\
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$

Умножим вторую строку на -4 и первую строку на 7

$\begin{pmatrix}
\left.\begin{matrix}
0 & -28 & 28 \\ 
0 & 28 & 4 \\
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
28\\ 
68\\
0
\end{matrix}
\end{pmatrix}$


Прибавим вторую строку к первой и поменяем местами строки

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & 28 & 4 \\
0 & 0 & 32 
\end{matrix}\right|
\begin{matrix}
0\\ 
68\\
96
\end{matrix}
\end{pmatrix}$



Ответ: Система совместна и имеет единственное решение

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$

Прибавим ко второй строке первую:

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
3 & -6 & 9 \\
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
1\\ 
-1\\
5
\end{matrix}
\end{pmatrix}$

Вычтем из третьей строки вторую:

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
3 & -6 & 9 \\
0 & 0 & 0 
\end{matrix}\right|
\begin{matrix}
1\\ 
-1\\
6
\end{matrix}
\end{pmatrix}$

Ответ: Система несовместна и не имеет решений

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8 
\end{matrix}\right|
\begin{matrix}
4\\ 
5
\end{matrix}
\end{pmatrix}$

Вычтем из второй строки утроенную первую:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0 & -5 & -23 
\end{matrix}\right|
\begin{matrix}
4\\ 
-7
\end{matrix}
\end{pmatrix}$

Ответ: Система совместна и имеет бесконечное количество решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Проверим на совместность с помощью теоремы Кронекера-Капелли:

$rank A = rank \tilde A = 4$ => система определена и совместна, то есть имеет единственное решение

In [1]:
import numpy as np

a = np.array([
    [1, 3, -2, 4],
    [0, 5, 0, 1],
    [0, 0, 3, 0],
    [0, 0, 0, 2]
])

a_b = np.array([
    [1, 3, -2, 4, 3],
    [0, 5, 0, 1, 2],
    [0, 0, 3, 0, 4],
    [0, 0, 0, 2, 1]
])


print(f'Ранг основной матрицы A\t\t{np.linalg.matrix_rank(a)}')
print(f'Ранг расширенной матрицы A\t{np.linalg.matrix_rank(a_b)}')

Ранг основной матрицы A		4
Ранг расширенной матрицы A	4


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Вычтем удвоенную первую строку из второй и утроенную первую строку из третьей строки:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}$

Вычтем удвоенную вторую строку из третьей:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a - 2(b-2a)
\end{matrix}
\end{pmatrix}$


$c-3a - 2(b-2a) = c-3a - 2b + 4a = c + a - 2b$

Если $c + a - 2b \ne 0$, то система несовместна и не имеет решений

## Тема: Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

a) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Найдем определитель:

$\begin{vmatrix}
1 & -2 \\ 
3 & -4 \\ 
\end{vmatrix} = 1 \cdot (-4) - 3 \cdot (-2) = -4 + 6 = 2$, $\Delta \ne 0$ => система уравнений определена, т.е. совместна.

Найдем $detA_{1}$, $detA_{2}$:

$x_{i}=\frac{detA_{i}}{detA}$

$detA_{1} = \begin{vmatrix}
1 & -2 \\ 
7 & -4 \\ 
\end{vmatrix} = -4 + 14 = -10$ => $x_1 = \frac{10}{2} = 5$

$detA_{2} = \begin{vmatrix}
1 & 1 \\ 
3 & 7 \\ 
\end{vmatrix} = 7 - 3 = 4$ => $x_2 = \frac{4}{2} = 2$

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Найдем определитель:

$\begin{vmatrix}
2 & -1 & 5 \\ 
1 & 1 & -3 \\ 
2 & 4 & 1
\end{vmatrix} = 2(1+12) + (1+6) + 5(4-2) = 26 + 7 + 10 = 43$, $\Delta \ne 0$ => система уравнений определена, т.е. совместна.

$detA_{1} = \begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1 
\end{vmatrix} = 10(1+12) + 1(-2+3) +5(-8-1) = 130 + 1 - 45 = 86$
 => $x_1 = \frac{86}{43}$

$detA_{2} = \begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1 
\end{vmatrix} = 2(-2+3) - 10(1+6) + 5(1+4) = 2 - 70 + 25 = -43$ => $x_2 = -\frac{43}{43} = -1$

$detA_{3} = \begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1 
\end{vmatrix} = 2(1+8) + 1(1+4) + 10(4-2) = 18 + 5 + 20 = 43$ => $x_3 = \frac{43}{43} = 1$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

a)
$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

Из второй строки отнимаем первую, умноженную на два

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$

Из третьей строки отнимаем первую, умноженную на три

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$

Из третьей строки отнимаем вторую, умноженную на четыре

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$


Составляем матрицу из коэффицентов, с помощью которых получили треугольную матрицу со знаком плюс:

L = $\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

U - наддиагональная часть преобразованной исходной матрицы

U = $\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

In [2]:
A = np.array([
    [1, 2, 4],
    [2, 9, 12],
    [3, 26, 30]
])

L = np.array([
    [1, 0, 0],
    [2, 1, 0],
    [3, 4, 1]
])

U = np.array([
    [1, 2, 4],
    [0, 5, 4],
    [0, 0, 2]
])

print(f'Матрица A: \n {A}')
print(f'Произведение матрицы L и U: \n {np.dot(L, U)}')

Матрица A: 
 [[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
Произведение матрицы L и U: 
 [[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


б) $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

Отнимаем от второй строки первую строку, умноженную на два

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

Отнимаем от третьей строки первую строку, умноженную на три

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4 & 22 & 53 & 33
\end{pmatrix}$

Отнимаем от третьей строки вторую строку, умноженную на пять

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
4 & 22 & 53 & 33
\end{pmatrix}$

Отнимаем от четвертой строки первую строку, умноженную на четыре

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 18 & 45 & 17
\end{pmatrix}$

Отнимаем от четвертой строки вторую строку, умноженную на шесть

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$

Отнимаем от четвертой строки третью строку, умноженную на семь

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

Составляем матрицу из коэффицентов, с помощью которых получили треугольную матрицу со знаком плюс:

L = $\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

U = $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

In [3]:
A = np.array([
    [1, 1, 2, 4],
    [2, 5, 8, 9],
    [3, 18, 29, 18],
    [4, 22, 53, 33]
    
])

L = np.array([
    [1, 0, 0, 0],
    [2, 1, 0, 0],
    [3, 5, 1, 0],
    [4, 6, 7, 1]
    
])

U = np.array([
    [1, 1, 2, 4],
    [0, 3, 4, 1],
    [0, 0, 3, 1],
    [0, 0, 0, 4]
    
])

print(f'Матрица A: \n {A}')
print(f'Произведение матрицы L и U: \n {np.dot(L, U)}')

Матрица A: 
 [[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]
Произведение матрицы L и U: 
 [[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Матрица коэффицентов:

$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4 \\
\end{pmatrix}$

Отнимем от второй строки первую строку, умноженную на 5.5, и от третьей строки первую, умноженную на 4.5:

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -11.5 \\ 
0 & 7/2 & -9.5 \\
\end{pmatrix}$

Отнимем от третьей строки вторую, умноженную на $\frac{7}{3}$:

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & 52/3 \\
\end{pmatrix}$


L = $\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 7/3 & 1 \\
\end{pmatrix}$

U = $\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & 52/3   \\
\end{pmatrix}$

In [4]:
A = np.array([
    [2, 1, 3],
    [11, 7, 5],
    [9, 8, 4]
])

L = np.array([
    [1, 0, 0],
    [5.5, 1, 0],
    [4.5, 7/3, 1]
])


U = np.array([
    [2, 1, 3],
    [0, 1.5, -11.5],
    [0, 0, 52/3]
])

print(f'Матрица A: \n {A}')
print(f'Произведение матрицы L и U: \n {np.dot(L, U)}')

Матрица A: 
 [[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]
Произведение матрицы L и U: 
 [[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]


$Ly = b$

$\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 7/3 & 1 \\
\end{pmatrix} \cdot \begin{pmatrix}
y_1 \\ 
y_2 \\ 
y_3
\end{pmatrix} = \begin{pmatrix}
1 \\ 
-6 \\ 
- 5
\end{pmatrix}$

$\begin{cases}
y_1=1, \\
5.5y_{1} + y_{2} =-6, \\
4.5y_{1} + \frac{7}{3}y_{2} + y_3 = - 5;
\end{cases}$

$\begin{cases}
y_1=1, \\
y_{2} =-11.5, \\
4.5 - \frac{7}{3} \cdot 11.5 + y_3 = - 5;
\end{cases}$

$\begin{cases}
y_1=1, \\
y_{2} =-11.5, \\
y_3 = \frac{52}{3};
\end{cases}$

$Ux = y$

$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & 52/3   \\
\end{pmatrix} \cdot \begin{pmatrix}
x_1 \\
x_2 \\
x_3
\end{pmatrix} = \begin{pmatrix}
1 \\ 
-11.5 \\ 
52/3
\end{pmatrix}$

$\begin{cases}
2x_1 + x_2 + 3x_3 =1, \\
1.5x_2 - 11.5x_3 =-11.5, \\
\frac{52}{3}x_3 = \frac{52}{3};
\end{cases}$

$\begin{cases}
x_3 = - 1, \\
x_2 = 0, \\
x_3 = 1;
\end{cases}$

Проверка:

In [5]:
b = np.array([1, -6, - 5])
y = np.array([1, -11.5, 52/3])

np.linalg.solve(L, b), np.linalg.solve(U, y)

(array([  1.        , -11.5       ,  17.33333333]), array([-1.,  0.,  1.]))