Анастасия Плавина

### Тема. Матрицы и матричные операции. Часть 1.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

**Решение:**

а) прозведения AB и BA не определены, т.к. количество строк и столбцов матриц A и B совпадает.

б) прозведение AB определено, размерность 2X3

в) произведения AB(8X8) и BА(3X3) определены
    
г) произведения AB и BA определены, обе матрицы 4Х4.

    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B = 
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


$A \cdot B = 
\begin{pmatrix}
(1 \cdot 4 + (-2) \cdot 0) & (1 \cdot (-1) + (-2)\cdot 5)\\ 
(3 \cdot 4 + 0 \cdot 0) & (3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}$

In [1]:
import numpy as np

A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print('Сумма матриц A и B\n', A+B)
print('Произведение матриц A и B\n', A.dot(B))

Сумма матриц A и B
 [[ 5 -3]
 [ 3  5]]
Произведение матриц A и B
 [[  4 -11]
 [ 12  -3]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A = 3\cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18 
\end{pmatrix}$


$2B = 2 \cdot \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix} = \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$


$4C= 4\cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$


$D = 3A - 2B + 4C = \begin{pmatrix}
3 & 21\\ 
9 & -18 
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}$

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$

$A\cdot A^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} = \begin{pmatrix}
(16+1) & (20 - 2) & (8+3)\\ 
(20 -2) & (25+4) & (10-6)\\ 
(8 -3) & (10-6) & (4+9)
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^{T} \cdot A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3 
\end{pmatrix} = \begin{pmatrix}
(16+25+4) & (4-10+6) \\ 
(4-10+6) & (1 + 4 +9)\\ 
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\ 
0 & 14\\ 
\end{pmatrix}$

In [3]:
A = np.array([
    [4, 1], 
    [5, -2],
    [2, 3]
])

In [4]:
A_T = A.T
A_T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [5]:
A.dot(A_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [6]:
A_T.dot(A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [7]:
def matrix_dot(A, B):
    """Перемножение двух матриц
    """
    
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for p in range(A.shape[1]):
                C[i][j] += A[i][p]*B[p][j]
    return C

matrix_dot(A, A_T) 

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

### Тема. Матрицы и матричные операции. Часть 2.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

**Решение:**

а) $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$

$\Delta = \sin^2 x + \cos^2 x = 1$

б) $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$ 

Матрица треугольная => определитель равен произведению членов главной диагонали:

$\Delta = 180 $


в) $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} \sim \begin{vmatrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
6 & 6 & 6
\end{vmatrix}$ =>

=> после вычитание первой строки из 2 и 3 строки матрицы видим, что 2 и 3 строки матрицы линейно зависимы => 
$\Delta = 0$

In [8]:
a = np.array([
    [np.sin(1), -np.cos(1)],
    [np.cos(1), np.sin(1)]
])
np.linalg.det(a)

1.0

In [9]:
b = np.array([
    [4, 2, 3],
    [0, 5, 1],
    [0, 0, 9]
])
np.linalg.det(b)

180.0

In [10]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
np.linalg.det(c)

0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
  

**Решение:**

a) $\Delta = 16$, т.к. для двух матриц одинакового размера верно $\Delta AB = \Delta A \cdot \Delta B$

б) $\Delta = 4$, т.к. определитель транспонированной матрицы равен определителю исходной матрицы

в) $\Delta = 4 \cdot 2^n$ для матрицы n $X$ n

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = -2 \cdot (-182 - 42) - 7\cdot (52 + 18) - 3 \cdot (28 - 42) = 448 - 490 + 42 = 0 $ 

In [11]:
a = np.array([
    [-2, 7, -3],
    [4, -14, 6],
    [-3, 7, 13]
])

np.linalg.det(a)

0.0

In [12]:
np.linalg.matrix_rank(a)

2

Определитель матрицы равен 0, ранг меньше 3 для матрицы 3 на 3 => матрица вырожденная


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

**Решение:**

а) 3 строка = сумма 1 и 2 строки => отбрасываем ее и получаем

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
\end{pmatrix}$

Вычтем 1-ую строку из 2-ой:

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
\end{pmatrix}$

Ранг матрицы = 2


б) 3 строка = сумма 1 и 2 строки => отбрасываем ее:

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$


Поменяем строки местами:

$\begin{pmatrix}
2 & 3 & 5 & 6\\
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2
\end{pmatrix}$

Ранг матрицы = 3

In [13]:
a = np.array([
    [1, 2, 3],
    [1, 1, 1],
    [2, 3, 4]
])

np.linalg.matrix_rank(a)

2

In [15]:
b = np.array([
    [0, 0, 2, 1],
    [0, 0, 2, 2],
    [0, 0, 4, 3],
    [2, 3, 5, 6]
])

np.linalg.matrix_rank(b)

3